### ISSUE TITLE
turn cheat on/off in settings 

### ISSUE THREAD

**Issue by MicroJOo** [jakobharder/burntime#2]
although godmode is off (default in the settings) i can spam items with key 1 and 2 

we should have a option in the launcher-settings to switch it on/off

**Comment by jakobharder** [comment]
I added an enable_cheats setting to disable the item spawns (and all other debug features).
For godmode I added a comment to say that it is only referring to the player's health.

Settings in launcher might make sense, but I'll consider it later.

**Comment by jakobharder** [comment]
added cheat settings with latest master commit 70c6749050e18b7fcacbe30dc548ca1c3939f89a
