### ISSUE TITLE
Map Editor Crashing because Tile-Folder is missing

### ISSUE THREAD

**Issue by MicroJOo** [jakobharder/burntime#4]
win 7 , 64bit

i double-click the "Burntime MapEditor.exe" and its crashing 

cant give you any more hints , because theres no log-output

*Edit :
i have managed to get it working by myself , i did copy the "tile-folder" from :

\bin\burntime\game\classic_newgfx\gfx

into

 \bin\tools\MapEditor

now it works ... but is that intended ? @jakobharder

**Comment by jakobharder** [comment]
intended? yes and no. a tiles/setname folder is required to add new tiles. the update will explain it in some words now - and the crash is removed.

**Comment by MicroJOo** [comment]
yeah , nevermind ... thanks
