### ISSUE TITLE
Fix for endgame crash

### ISSUE THREAD

**Issue by spiritplumber** [jakobharder/burntime#42]
Sometimes if you overfill a location with food (for example New Village at the endgame) you get a null pointer.

This is a temporary fix in Location.cs to fix that. It's an ugly fix but it will let you finish/win the game :)

        public Item FindFood(out IItemCollection owner)
        {
            Item item = null;
            owner = null;

            for (int i = 0; i < Rooms.Count; i++)
            {
                for (int j = 0; j < Rooms[i].Items.Count; j++)
                {
                    if (Rooms[i].Items[j].FoodValue != 0)
                    {
                        try
                        {
                            if (item == null || item.FoodValue < Rooms[i].Items[j].FoodValue || item.Type == Production.Produce)
                            {
                                item = Rooms[i].Items[j];
                                owner = Rooms[i].Items;
                            }
                        }
                        catch (Exception)
                        {
                          // log this to get more clarity, but just adding this lets me finish the game
                        }
                    }
                }
            }

            return item;
        }

**Comment by jakobharder** [comment]
Oh, nice. Thanks for finding and reporting that issue!
