### ISSUE TITLE
Stuck in New Village

### ISSUE THREAD

**Issue by MicroJOo** [jakobharder/burntime#5]
when i enter the village i stuck in those trees ... cant move inside the village 

![stuck](https://cloud.githubusercontent.com/assets/9139965/8034587/51820198-0de9-11e5-86ff-77a7b632be84.png)

**Comment by jakobharder** [comment]
Entry point fixed with d9905722bee973a235578afb1a29a39d8e5553f7
Other parts of New Village are still in progress (e.g. NPCs).
